### PR TITLE
Terraform example added

### PR DESCRIPTION
**Pull request by knowledgegainer1**
Here i have added terraform provider syntax to refer.

### CODE REVIEW

**Review by GOTTAMREDDY — DISMISSED** [review]
aggreed

**Review by GOTTAMREDDY — DISMISSED** [review]
ok

**Review by GOTTAMREDDY — COMMENTED** [review]
there is some mistake in code

**Comment by knowledgegainer1** [comment]
> there is some mistake in code

what is the miakte

**Comment by GOTTAMREDDY** [comment]
> > there is some mistake in code
> 
> what is the miakte

check the code

**Review by GOTTAMREDDY — APPROVED** [review]

**Comment by knowledgegainer1** [comment]
compmeted

**Pull request merged**
